export const SPACES = [
  { id: "products", en: "Products", ko: "제품", sign: "THE PRODUCT GALLERY", position: [-5, 3.7, 4.2], rotation: 0, color: 0xce8057,
    summary: { title: { en: "Ideas, out in the world.", ko: "아이디어가 세상으로." }, body: { en: "An onchain exchange, everyday apps, and AI tools. Products I've built, shipped, and cared for — all in one gallery.", ko: "온체인 거래소부터 일상의 앱, AI 도구까지. 직접 만들고 출시하고 운영해 온 제품을 만나보세요." }, action: { en: "Explore the products", ko: "제품 자세히 보기" } } },
  { id: "capabilities", en: "Practice", ko: "역량", sign: "THE WORKSHOP", position: [-4.5, 9.5, 3.9], rotation: 0, color: 0xe4ac48,
    summary: { title: { en: "Clarity. From the ground up.", ko: "본질에 집중하고, 기초부터 단단하게." }, body: { en: "One engineer, from architecture to launch. Web, mobile, scalable backends, and AI — every layer considered, every detail connected.", ko: "설계부터 출시까지, 한 명의 개발자가. 웹, 모바일, 확장 가능한 백엔드와 AI를 하나의 제품으로 연결합니다." }, action: { en: "Inside the practice", ko: "개발 역량 살펴보기" } } },
  { id: "subscription", en: "Work together", ko: "함께 만들기", sign: "THE PARTNERSHIP PAVILION", position: [-4, 15.3, 3.6], rotation: 0, color: 0xf1bc50,
    summary: { title: { en: "Built to work. Room to grow.", ko: "제대로 작동하고, 자연스럽게 자라도록." }, body: { en: "A dedicated engineer, one request at a time. A flat monthly partnership to build, launch, and keep improving your product.", ko: "전담 개발자와 한 번에 하나씩. 정해진 월 비용으로 제품을 만들고, 출시하고, 꾸준히 개선합니다." }, action: { en: "See the partnership", ko: "협업 방식 알아보기" } } },
  { id: "stack", en: "Stack", ko: "기술", sign: "THE MATERIAL LIBRARY", position: [-3.5, 21.1, 3.3], rotation: 0, color: 0xe6b55a,
    summary: { title: { en: "The tools behind the work.", ko: "제품을 지탱하는 기술." }, body: { en: "The languages, frameworks, and infrastructure I use to turn an idea into a working system.", ko: "아이디어를 실제로 작동하는 시스템으로 만드는 언어, 프레임워크, 인프라를 소개합니다." }, action: { en: "Explore the stack", ko: "기술 스택 보기" } } },
  { id: "media", en: "Press", ko: "보도", sign: "THE PRESS ROOM", position: [-14.7, 3.7, 3.6], rotation: 0, color: 0xdca44f,
    summary: { title: { en: "Stories beyond the studio.", ko: "스튜디오 밖의 이야기." }, body: { en: "A home for interviews, podcasts, and press as they publish. For now, the door is open to press enquiries.", ko: "인터뷰, 팟캐스트, 언론 보도를 공개되는 대로 모읍니다. 취재나 대화를 제안하고 싶다면 연락 주세요." }, action: { en: "Visit the press room", ko: "보도 공간 보기" } } },
  { id: "contact", en: "Contact", ko: "연락", sign: "THE CONVERSATION COURT", position: [4.8, 3.7, 1.2], rotation: 0, color: 0xcc9160,
    summary: { title: { en: "It starts with a conversation.", ko: "시작은 대화입니다." }, body: { en: "Tell me what you're trying to ship. Let's find the next step from first idea to a product people can use.", ko: "무엇을 출시하고 싶은지 들려주세요. 첫 아이디어를 사람들이 쓰는 제품으로 만들 다음 단계를 함께 찾습니다." }, action: { en: "Start a conversation", ko: "대화 시작하기" } } },
];
